name: coverage
on: [push]
jobs:

  linux-coverage:
    name: linux
    runs-on: [ ubuntu-22.04 ]
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        submodules: recursive

    - name: Install libs
      run: |
        sudo apt-get install -y libmbedtls-dev ninja-build pip python3-pip mosquitto-clients pkg-config libmysqlclient-dev sqlite3
        pip install Jinja2 paho-mqtt

    - name: Install MQTTX_cli
      run: |
        curl -LO https://www.emqx.com/en/downloads/MQTTX/v1.9.10/mqttx-cli-linux-arm64
        sudo install ./mqttx-cli-linux-arm64 /usr/local/bin/mqttx_cli

    - name: Install AWS SDK
      run: |
          wget https://github.com/aws/aws-iot-device-sdk-embedded-C/releases/download/202108.00/aws-iot-device-sdk-embedded-C-202108.00.zip
          unzip aws-iot-device-sdk-embedded-C-202108.00.zip
          cd aws-iot-device-sdk-embedded-C && mkdir build && cd build && cmake -G Ninja -DBUILD_DEMOS=OFF -DCMAKE_C_STANDARD=99 -DINSTALL_TO_SYSTEM=ON .. && ninja && sudo ninja install && sudo cp ../demos/logging-stack/logging_*.h  /usr/local/include/aws/ && sudo ldconfig
      
    - name: Configure
      run:  mkdir build && cd build && cmake -G Ninja -DNANOMQ_TESTS=ON -DDEBUG=ON -DASAN=ON -DNNG_ENABLE_COVERAGE=ON -DNNG_ENABLE_TLS=ON -DNNG_ENABLE_SQLITE=ON -DENABLE_RULE_ENGINE=ON -DENABLE_MYSQL=ON -DENABLE_AWS_BRIDGE=ON -DNNG_ENABLE_QUIC=OFF ..

    - name: build
      run: cd build && ninja

    - name: Test
      run: cd build && ctest --output-on-failure

    - name: Upload report
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        yml: ./.codecov.yml
