name: coverage
on: [push]
jobs:

  linux-coverage:
    name: linux
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install libs
      run: |
        sudo apt-get install -y libmbedtls-dev ninja-build pip python3-pip mosquitto-clients
        pip install Jinja2 paho-mqtt

    - name: Configure
      run:  mkdir build && cd build && cmake -G Ninja -DNANOMQ_TESTS=ON -DDEBUG=ON -DASAN=ON -DNNG_ENABLE_COVERAGE=ON -DNNG_ENABLE_TLS=ON -DNNG_ENABLE_SQLITE=ON -DENABLE_RULE_ENGINE=ON ..

    - name: build
      run: cd build && ninja

    - name: Test
      run: cd build && ctest --output-on-failure

    - name: Upload report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        yml: ./.codecov.yml
