name: Function test

on:
  push:
    branches:
      - master
      - moi_0_18_1
  pull_request:
  release:
    types:
    - published

jobs:
  function_test:
    runs-on: ["self-hosted","ephemeral","linux","x64"]

    steps:
    - name: install lib
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build rpm pip python3-pip mosquitto-clients netcat
        pip install Jinja2
        pip install paho-mqtt

    - uses: actions/checkout@v3
    - run: git submodule update --init nng

    - name: build
      run: |
        set -eu
        git clone https://github.com/Mbed-TLS/mbedtls.git && cd mbedtls
        git reset --hard 919ff15ec
        mkdir build && cd build
        cmake ..
        cmake --build .
        sudo make install
        cd ../..

        mkdir -p build
        cd build
        cmake -DDEBUG=ON -DASAN=ON -DNNG_ENABLE_TLS=ON -DNOLOG=OFF ..
        make
        sudo make install
    - name: test
      run: |
        python3 .github/scripts/test.py 
